created account POST and GET
CodeSarge/web-banking pull request #21
Opened 2021-06-25 17:46 UTC by andy-sam

Fixes #19

2021-06-26 05:31 UTC, alex-anakin requested changes

2021-06-26 06:18 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/AccountRepository.java
> +}
done

2021-06-26 06:20 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/UserRepository.java
> +
done

2021-06-26 06:47 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/AccountService.java
> +        return account;
done

2021-06-26 19:55 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/AccountService.java
> +        return accountRepository.findAllById(Collections.singleton(id));
I tried

2021-06-26 20:29 UTC, andy-sam commented on src/main/java/com/codesarge/banking/controllers/AccountController.java
> +        return accountService.saveAccount(account);
I tried

2021-06-26 20:32 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/AccountService.java
> +        accountRepository.save(account);
I tried

2021-06-30 17:58 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/AccountService.java
> +        accountRepository.save(account);
done I think

2021-07-04 06:59 UTC, alex-anakin approved these changes

2021-07-04 06:59 UTC, alex-anakin commented on src/test/resources/application.properties
> +spring.datasource.driver-class-name=org.h2.Driver
add an empty line

2021-07-04 06:59 UTC, alex-anakin commented on src/test/java/com/codesarge/banking/controllers/AccountControllerIntegrationTest.java
> +        // find method for mokMVC for check out response entity
make this comment a TODO

2021-07-04 06:59 UTC, alex-anakin commented on src/test/java/com/codesarge/banking/controllers/AccountControllerIntegrationTest.java
> +    private AccountRepository accountRepository;
remove it and run the test. Probably it will work.

2021-07-04 06:59 UTC, alex-anakin commented on src/test/java/com/codesarge/banking/controllers/AccountControllerIntegrationTest.java
> +    private UserRepository userRepository;
remove it and run the test. Probably it will work.

2021-07-04 06:59 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/service/AccountService.java
> +    private UserRepository userRepository;
Wire fields through the constructor.

2021-07-04 06:59 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/entities/Account.java
> +    public static String openNewAccount() {
Let's move it to the `utils/AccountGenerator` class

2021-07-04 06:59 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/entities/Account.java
> +import javax.persistence.*;
don't use wildcard imports

2021-07-04 07:00 UTC, merged

2021-07-04 18:40 UTC, andy-sam commented on src/test/resources/application.properties
> +spring.datasource.driver-class-name=org.h2.Driver
done

2021-07-04 18:42 UTC, andy-sam commented on src/test/java/com/codesarge/banking/controllers/AccountControllerIntegrationTest.java
> +        // find method for mokMVC for check out response entity
done

2021-07-04 18:46 UTC, andy-sam commented on src/test/java/com/codesarge/banking/controllers/AccountControllerIntegrationTest.java
> +    private AccountRepository accountRepository;
done. App is working. I need you explain it again for me if you don't mind

2021-07-04 18:48 UTC, andy-sam commented on src/test/java/com/codesarge/banking/controllers/AccountControllerIntegrationTest.java
> +    private UserRepository userRepository;
done. It's working

2021-07-04 19:02 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/AccountService.java
> +    private UserRepository userRepository;
done. I deleted also  private UserService userService. Everything is working.

2021-07-04 19:14 UTC, andy-sam commented on src/main/java/com/codesarge/banking/entities/Account.java
> +    public static String openNewAccount() {
done

2021-07-04 19:14 UTC, andy-sam commented on src/main/java/com/codesarge/banking/entities/Account.java
> +import javax.persistence.*;
done