Add fields to the account entity
CodeSarge/web-banking pull request #27
Opened 2021-07-05 08:12 UTC by andy-sam

Fixes #24

2021-07-05 08:14 UTC, andy-sam commented
I made 1 issue from 2 yet

2021-07-06 06:40 UTC, alex-anakin requested changes

2021-07-06 06:40 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/entities/Account.java
> +    private Date date;
name the field `expirationDate`

2021-07-06 06:40 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/entities/AccountDto.java
> +    private Date date;
expirationDate

2021-07-06 06:40 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-07-04-01.yaml
> +#                  defaultValue: now()
remove

2021-07-06 06:40 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/entities/Account.java
> +    public Account(User user, Currency currency) {
add expDate initialization using Java Date API:
now() + 2 years

2021-07-06 06:40 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-07-05-01.yaml
> +                  value: now()
use dates from the task, for example, '2023-07-00'

2021-07-06 07:01 UTC, andy-sam commented on src/main/java/com/codesarge/banking/entities/Account.java
> +    private Date date;
done

2021-07-06 07:01 UTC, andy-sam commented on src/main/java/com/codesarge/banking/entities/AccountDto.java
> +    private Date date;
done

2021-07-06 07:02 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-07-04-01.yaml
> +#                  defaultValue: now()
done

2021-07-06 07:02 UTC, andy-sam commented on src/main/java/com/codesarge/banking/entities/Account.java
> +    public Account(User user, Currency currency) {
done

2021-07-06 07:16 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-07-05-01.yaml
> +                  value: now()
done

2021-07-06 07:17 UTC, alex-anakin approved these changes

2021-07-06 07:17 UTC, merged