added subsription table and entity
CodeSarge/web-banking pull request #40
Opened 2021-07-14 21:09 UTC by andy-sam

Fixes #38

2021-07-14 21:09 UTC, andy-sam commented
but it's not working yet
I have added changelog and Entity class but the table is not created in DB. App worked.
I added entity and then the app felled 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: Illegal attempt to map a non collection as a @OneToMany, @ManyToMany or @CollectionOfElements: com.codesarge.banking.entities.Account.id

2021-07-15 06:09 UTC, alex-anakin requested changes
You forgot to specify the new changelog in the master changelog. Fix it and try to run the app again.

2021-07-15 07:16 UTC, alex-anakin commented
The task description is updated. Add a date field to the table.

2021-07-16 06:21 UTC, alex-anakin approved these changes

2021-07-16 06:21 UTC, merged