Add subscription to bank services api #37
CodeSarge/web-banking pull request #41
Opened 2021-07-16 12:39 UTC by andy-sam

fixes #37

2021-07-17 21:04 UTC, alex-anakin requested changes
Just one more thing. You implemented SubscriptionResponseDto as a wrapper of SubscriptionDto. So it's redundant. Please remove SubscriptionResponseDto at all and return SubscriptionDto instead.

Everything else looks great.

2021-07-17 21:04 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/controllers/SubscriptionController.java
> +                .getUserId() + " and account # " + +subscriptionRequestDto.getAccountId());
redundant plus is here. please remove

2021-07-17 21:04 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +//        withdraw money (service payment) from the account
redundant comment. please remove

2021-07-17 21:18 UTC, andy-sam commented on src/main/java/com/codesarge/banking/controllers/SubscriptionController.java
> +                .getUserId() + " and account # " + +subscriptionRequestDto.getAccountId());
done

2021-07-17 21:18 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +//        withdraw money (service payment) from the account
done

2021-07-17 21:36 UTC, andy-sam commented
file:///home/andreew/Pictures/Screenshot%20from%202021-07-18%2000-21-19.png
/home/andreew/Pictures/Screenshot%20from%202021-07-18%2000-24-09.png

2021-07-18 05:39 UTC, alex-anakin approved these changes

2021-07-18 14:57 UTC, merged