Restrict subscribing user to the same bank service more than once #44
CodeSarge/web-banking pull request #53
Opened 2021-07-31 17:42 UTC by andy-sam

fixes #44

2021-08-01 07:03 UTC, alex-anakin requested changes

2021-08-01 07:03 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-07-20-SubscriptionCanceling.yaml
> +                  type: date
date -> datetime

2021-08-01 07:03 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/controllers/UserController.java
> +
redundant empty line, please remove

2021-08-01 07:03 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/entities/Subscription.java
> +
redundant empty lines, please remove

2021-08-01 07:03 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    List<Subscription> findSubscriptionsByAccountId(Long accountId);
unused method, please remove

2021-08-01 18:58 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    List<Subscription> findSubscriptionsByAccountUserId(Long accountId);
done

2021-08-01 18:59 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    List<Subscription> findSubscriptionsByAccountUserIdAndCanceledDateIsNull(Long accountId);
done

2021-08-01 19:00 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    List<Subscription> findSubscriptionsByAccountUserIdAndCanceledDateIsNotNull(Long accountId);
done

2021-08-01 19:02 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +                .findSubscriptionsByAccountUserId(account.getId());
done

2021-08-01 19:03 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +        for (Subscription s : allSubscriptionsOfUser) {
done

2021-08-01 19:06 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +                if (s.getBankService().getPeriodicity().equals(Periodicity.WEEKLY) || s
done

2021-08-01 19:10 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-07-20-SubscriptionCanceling.yaml
> +                  type: date
done

2021-08-01 19:10 UTC, andy-sam commented on src/main/java/com/codesarge/banking/controllers/UserController.java
> +
done

2021-08-01 19:11 UTC, andy-sam commented on src/main/java/com/codesarge/banking/entities/Subscription.java
> +
done

2021-08-01 19:12 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    List<Subscription> findSubscriptionsByAccountId(Long accountId);
done

2021-08-02 06:27 UTC, alex-anakin approved these changes

2021-08-02 19:14 UTC, merged