Create api for cancelling a recurring subscription #45
CodeSarge/web-banking pull request #54
Opened 2021-07-31 18:28 UTC by andy-sam

fixes #45

2021-08-01 07:37 UTC, alex-anakin requested changes

2021-08-01 07:37 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/controllers/SubscriptionController.java
> +    public ResponseEntity<SubscriptionDto> cencelSubscription(
censel -> cancel

2021-08-01 07:37 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    List<Subscription> findSubscriptionsByAccountId(Long accountId);
please remove

2021-08-01 07:37 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +        Subscription subscription = subscriptionRepository.getById(subscriptionId);
wrap this call in try/catch
in `catch` block handle `Exception` and return null

2021-08-01 07:37 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +        if (subscription.getBankService().getPeriodicity().equals(Periodicity.WEEKLY) ||
extract a variable `subscription.getBankService().getPeriodicity()`

2021-08-01 07:37 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +            if (subscription.getCanceledDate() == null) {
combine in one `if` statement with previous conditions

2021-08-01 07:37 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +                subscriptionRepository.save(subscription);
move saving before creating a DTO

2021-08-01 19:23 UTC, andy-sam commented on src/main/java/com/codesarge/banking/controllers/SubscriptionController.java
> +    public ResponseEntity<SubscriptionDto> cencelSubscription(
done

2021-08-01 19:28 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    List<Subscription> findSubscriptionsByAccountId(Long accountId);
done

2021-08-01 19:31 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +        if (subscription.getBankService().getPeriodicity().equals(Periodicity.WEEKLY) ||
done

2021-08-01 19:35 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +            if (subscription.getCanceledDate() == null) {
done

2021-08-01 19:36 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +                subscriptionRepository.save(subscription);
done

2021-08-01 19:41 UTC, andy-sam commented on src/main/java/com/codesarge/banking/service/SubscriptionService.java
> +        Subscription subscription = subscriptionRepository.getById(subscriptionId);
done

2021-08-02 06:30 UTC, alex-anakin approved these changes

2021-08-02 19:32 UTC, merged