implemented Bank services subscribers report
CodeSarge/web-banking pull request #72
Opened 2021-09-10 08:51 UTC by andy-sam

fixes #71

2021-09-14 18:58 UTC, alex-anakin requested changes

2021-09-14 21:08 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/BankServicesSubscribersRepository.java
> +    @Query(value = " SELECT  counting_date AS ReportingDate, one_time_amount AS OneTimeAmount,weekly_amount AS WeeklyAmount,monthly_amount AS MonthlyAmount FROM bank_services_subscriber " +
done

2021-09-14 21:09 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/BankServicesSubscribersRepository.java
> +    List<BankServicesSubscriberResult> countTypesOfBankServicesSubscribers();
done

2021-09-14 21:32 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-09-10-bankServiceSubscriber.yaml
> +                  type: BIGINT
done

2021-09-14 21:32 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-09-10-bankServiceSubscriber.yaml
> +                  type: BIGINT
done

2021-09-14 21:32 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-09-10-bankServiceSubscriber.yaml
> +                  type: BIGINT
done

2021-09-15 21:21 UTC, andy-sam commented on src/main/java/com/codesarge/banking/repositories/SubscriptionRepository.java
> +    int countOfMonthlySubscriptions();
done

2021-09-16 07:07 UTC, alex-anakin approved these changes

2021-09-16 07:07 UTC, merged