added LiquiBase
CodeSarge/web-banking pull request #8
Opened 2021-06-18 19:58 UTC by andy-sam

2021-06-19 20:16 UTC, alex-anakin requested changes

2021-06-19 20:16 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                    nullable: false
we don't need `username` column, please remove

2021-06-19 20:16 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                  type: varchar(50)
please add an empty line

2021-06-19 20:16 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                  name: first_name
please add a not-null constraint

2021-06-19 20:16 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                  name: last_name
please add a not-null constraint

2021-06-19 20:16 UTC, alex-anakin commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                  name: email
please add a not-null constraint

2021-06-19 20:16 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/User.java
> +public class User implements Serializable {
use Lombok for getters and setters

2021-06-19 20:16 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/User.java
> +    private String userName;
please remove this field

2021-06-19 20:16 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "password", nullable = false)
please check out, do we need to specify column name if it's equal to the field name

2021-06-19 20:16 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "first_name")
nullable = false

2021-06-19 20:16 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "last_name")
nullable = false

2021-06-19 20:16 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "email")
nullable = false

2021-06-19 20:16 UTC, alex-anakin commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "id")
please check out, do we need to specify column name if it's equal to the field name

2021-06-20 04:46 UTC, andy-sam commented on src/main/resources/application.properties
> +#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
done

2021-06-20 04:47 UTC, andy-sam commented on src/main/resources/application.properties
>  #spring.jpa.show-sql: true
done

2021-06-20 04:50 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                    nullable: false
done

2021-06-20 04:52 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                  type: varchar(50)
done

2021-06-20 04:54 UTC, andy-sam commented on src/main/resources/db/changelog/changelog-2021-06-18-01.yaml
> +                  name: first_name
done

2021-06-20 04:58 UTC, andy-sam commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "password", nullable = false)
deleted field "username"

2021-06-20 05:11 UTC, andy-sam commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "first_name")
I didn't understand what you mean =(

2021-06-20 05:12 UTC, andy-sam commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "last_name")
done

2021-06-20 05:16 UTC, andy-sam commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "email")
done

2021-06-20 05:17 UTC, andy-sam commented on src/main/java/com/codesarge/banking/User.java
> +    @Column(name = "id")
column name is deleted

2021-06-20 06:28 UTC, alex-anakin approved these changes

2021-06-20 06:29 UTC, merged